apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: httpbin
spec:
  hosts:
  - httpbin
  addresses:
  - 35.202.165.84
  ports:
  - number: 80
    name: http-port
    protocol: HTTP
  resolution: NONE
